### ISSUE TITLE
DELETE fails on collection if not empty

### ISSUE THREAD

**Issue by perry-mitchell** [OpenMarshal/npm-WebDAV-Server#14]
Sending a request like `DELETE /sub1` will fail if `/sub1` is not an empty directory.

The offending section of code can be found [here](https://github.com/OpenMarshal/npm-WebDAV-Server/blob/master/src/server/v2/commands/Delete.ts#L10). Logging the error object produces the following:

```
{ Error: ENOTEMPTY: directory not empty, rmdir '/Users/perry/git/webdav-client/test/testContents/sub1'
  errno: -66,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',
  path: '/Users/perry/git/webdav-client/test/testContents/sub1' }
```

As per [RFC4918](https://www.ietf.org/rfc/rfc4918.txt) I believe collections should be deleted regardless of contents:

> The DELETE method on a collection MUST act as if a "Depth: infinity" header was used on it.  A client MUST NOT submit a Depth header with a DELETE on a collection with any value but infinity.

I believe the method used to delete physical files is in error - perhaps using something like [rimraf](https://www.npmjs.com/package/rimraf) would be best?

_Side-note: Apologies for all the issues! Really enjoying using your library and by reimplementing mine I guess I'm indirectly testing a lot of functionality. Keep up the good work!_

**Comment by AdrienCastex** [comment]
Hello,

The problem was that the `PhysicalFileSystem` ignored the depth.

The problem is technically fixed in the version `2.2.1`.
I let you close the issue if you think that the problem is gone.

Thank you for your contribution.

*Side-note: Don't worry, issues are a great way to improve the stability of the library, so I am glad you reported the problem. And, I also like solving problems.*

**Comment by perry-mitchell** [comment]
Great! It looks like it works now.

Just noticed that you missed a [console.log](https://github.com/OpenMarshal/npm-WebDAV-Server/commit/da9abf0be569d53e9bfb2d833b2b8faae335caa3#diff-e679292ef5e46de92b3eb9eda29d4f9aR113) however..

Thanks for the quick response.

**Comment by AdrienCastex** [comment]
I forgot to remove them, thank you.
I removed them in the version `2.2.2`.
