### ISSUE TITLE
Encode special characters

### ISSUE THREAD

**Issue by F145h** [OpenMarshal/npm-WebDAV-Server#22]
I have troubles while using space character in filename for webdav.PhysicalFileSystem((and mb others) with WinSCP(in Windows) or CloudDuck(Mac OS X).

feel free to contact me.

**Comment by AdrienCastex** [comment]
Hello,

Indeed, *WinSCP* has trouble with unencoded white spaces.
I fixed the problem (`v2.3.8`) and it should not happen with other special character anymore. I encoded the file name and the URL of the resources.
I could not try with *CloudDuck* on *Mac OS X*, so please, try with the patched version and tell me if the problem is still occurring.

I let you close the issue if you think that the problem is gone.
Thank you very much for your contribution.

**Comment by F145h** [comment]
Thanks, good work. WinSCP works fine. unicode chars & space work in Windows Explorer and Mac OS X Finder. But cyberduck 2 still doesn't display files with the white space on mac os x. I'm not sure, but possibly that is its problem. I will research for this behaviour later. 

Also I have some strange Finder(OS X) behaviours, but I need to add more logging.

**Comment by AdrienCastex** [comment]
I cannot try on Mac OS X, because I don't have it.

I tried with Cyberduck 6.2.11 (Windows), WinSCP 5.11.2 (Windows), Nautilus (Ubuntu), Cadaver (Ubuntu), BitKinex 3.2.3 (Windows), WebDAV Redirector (Windows) GUI and command line (`NET USE [...]`). All seems to work with the new version `2.3.9` of `webdav-server`.

[Nautlius was having some trouble with encoded names](https://github.com/OpenMarshal/npm-WebDAV-Server/issues/11#issuecomment-341630106), but I fixed the issue I was encountering. Maybe that fixed the strange behaviour of Finder.

Can I have more information about the version of Cyberduck which causes trouble please?

Thank you for you help.

**Comment by F145h** [comment]
Great job!

I don't see any encodings problem with my WebDAV clients in the latest version!

And the last strange behavior of os x finder is duplicating entries in a file listing. This lasts for a second: folders and files are duplicated, and then they disappear. I have not seen this on any of the WebDAV clients. Windows Explorer is fine, too, this concerns only the finder.

I will try to add logging for _fastExistCheck() and _readDir() calls, hope it would help
